name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "@Iamzanis0308" | docker login -u "josh9" --password-stdin
      - run: docker build -t josh9/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true josh9/react-test npm test

      - run: docker build -t josh9/multi-client ./client
      - run: docker build -t josh9/multi-nginx ./nginx
      - run: docker build -t josh9/multi-server ./server
      - run: docker build -t josh9/multi-worker ./worker

      - run: docker push josh9/multi-client
      - run: docker push josh9/multi-nginx
      - run: docker push josh9/multi-server
      - run: docker push josh9/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
